export const starterTemplates = [
  {
    type: 'angular-standalone',
    typeName: 'New Angular Project',
    name: 'list',
    description: 'A starting project with a list',
    targets: 'ionic-targets',
  },
  {
    type: 'angular-standalone',
    typeName: 'New Angular Project',
    name: 'blank',
    description: 'A blank starter project',
    targets: 'ionic-targets',
  },
  {
    type: 'angular-standalone',
    typeName: 'New Angular Project',
    name: 'sidemenu',
    description: 'A starting project with a side menu with navigation in the content area',
    targets: 'ionic-targets',
  },
  {
    type: 'angular-standalone',
    typeName: 'New Angular Project',
    name: 'tabs',
    description: 'A starting project with a simple tabbed interface',
    targets: 'ionic-targets',
  },
  {
    type: 'react',
    typeName: 'New React Project',
    name: 'tabs',
    description: 'A starting project with a simple tabbed interface',
    targets: 'ionic-targets',
  },
  {
    type: 'react',
    typeName: 'New React Project',
    name: 'sidemenu',
    description: 'A starting project with a side menu with navigation in the content area',
    targets: 'ionic-targets',
  },
  {
    type: 'react',
    typeName: 'New React Project',
    name: 'list',
    description: 'A starting project with a list',
    targets: 'ionic-targets',
  },
  {
    type: 'react',
    typeName: 'New React Project',
    name: 'blank',
    description: 'A blank starter project',
    targets: 'ionic-targets',
  },
  {
    type: 'vue',
    typeName: 'New Vue Project',
    name: 'list',
    description: 'A starting project with a list',
    targets: 'ionic-targets',
  },
  {
    type: 'vue',
    typeName: 'New Vue Project',
    name: 'blank',
    description: 'The official blank starter project',
    targets: 'ionic-targets',
  },
  {
    type: 'vue',
    typeName: 'New Vue Project',
    name: 'sidemenu',
    description: 'The official starting project with a side menu with navigation in the content area',
    targets: 'ionic-targets',
  },
  {
    type: 'vue',
    typeName: 'New Vue Project',
    name: 'tabs',
    description: 'The official starting project with a simple tabbed interface with Ionic Framework',
    targets: 'ionic-targets',
  },
  {
    type: 'plugin',
    typeName: 'New Capacitor Plugin',
    name: 'Starter',
    url: 'https://capacitorjs.com/docs/plugins/creating-plugins',
    description: 'The official Capacitor plugin project',
    targets: '',
  },
  {
    type: 'custom-angular',
    typeName: 'New Angular Project',
    name: 'Starter',
    url: 'https://angular.dev/installation#instructions',
    description: 'The official empty starter project for Angular',
    commands: ['npm install -g @angular/cli', 'ng new $(project-name)'],
    targets: '',
  },
  {
    type: 'custom-svelte',
    typeName: 'New Svelte Project',
    name: 'Minimal',
    url: 'https://svelte.dev/docs/svelte/getting-started',
    description: 'The official minimal starter project for Svelte',
    commands: ['npx sv create $(project-name) --template minimal --types ts --no-add-ons --no-install'],
  },
  {
    type: 'custom-svelte',
    typeName: 'New Svelte Project',
    name: 'Demo',
    url: 'https://svelte.dev/docs/svelte/getting-started',
    description: 'The official demo starter project for SvelteKit',
    commands: ['npx sv create $(project-name) --template demo --types ts --no-add-ons --no-install'],
  },
  {
    type: 'custom-svelte',
    typeName: 'New Svelte Project',
    name: 'Library',
    url: 'https://svelte.dev/docs/svelte/getting-started',
    description: 'The official starter project for SvelteKit Library',
    commands: ['npx sv create $(project-name) --template library --types ts --no-add-ons --no-install'],
  },
  {
    type: 'custom-ionic-svelte',
    typeName: 'New Svelte Project with Ionic Framework',
    name: 'Starter',
    description: 'A community starter project for Svelte with Ionic Framework',
    url: 'https://github.com/Tommertom/svelte-ionic-app',
    commands: ['npm create ionic-svelte-app@latest'],
  },
];

export const frameworks = [
  { name: 'Ionic Angular', icon: 'angular', icon2: 'ionic', type: 'angular-standalone' },
  { name: 'Ionic React', icon: 'react', icon2: 'ionic', type: 'react' },
  { name: 'Ionic Vue', icon: 'react', icon2: 'ionic', type: 'vue' },
  { name: 'Ionic Svelte', icon: 'svelte', icon2: 'ionic', type: 'custom-ionic-svelte' },
  { name: 'Angular', icon: 'angular', type: 'custom-angular' },
  { name: 'Svelte', icon: 'svelte', type: 'custom-svelte' },
  { name: 'Capacitor Plugin', icon: 'capacitor', type: 'plugin' },
];

export const targets = [
  {
    name: 'ionic-targets',
    targets: [
      { name: 'Web', icon: 'web', appearance: 'selected' },
      { name: 'iOS', icon: 'apple' },
      { name: 'Android', icon: 'android' },
    ],
  },
];
